version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  Niranjan-Circle-CI:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
    Niranjan-Circle-CI:
      jobs:
        - Niranjan-Circle-CI